branch-defaults:
  master:
    environment: tweetsuite
global:
  application_name: TweetSuite
  default_ec2_keyname: aws-eb
  default_platform: Python 2.7
  default_region: us-west-1
  profile: eb-cli
  sc: git
